# -*- coding: utf-8 -*-
"""labwork1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I_4k9HUXe07oqX6x6eZHGPEJj3cx-iW4
"""

#Ex1
import math

radius = float(input("Enter circle radius: "))

area = 3.14 * radius ** 2

print("Circle area =",
round(area, 1))

#Ex2
celsius = float(input("Enter the temperature in Celsius: "))
fahrenheit = (celsius * 9 / 5) + 32
c_str = int(celsius) if celsius.is_integer() else celsius
print(celsius, "(C) ="),
fahrenheit, "(F)"

#Ex3
n = int(input("Enter a number? "))

if n < 2:
  print(n, "is a NOT prime number")
else:
  prime = True
  for i in range(2, n):
      if n % i == 0:
          prime = False
          break

  if prime:
      print(n, "is a prime number")
  else:
      print(n, "is a NOT prime number")

#Ex4
n = int(input("Enter a number?"))

sum = 0
for i in range(1, n):
    if n % i == 0:
      sum += i

if sum == n:
  print(n, "is a perfect number")
else:
  print(n, "is a NOT perfect number")

#Ex5
colors = ["Blue", "Yellow", "Green", "Red", "Black"]

color = input("What is your favorite color? ")

if color in colors:
  print("Your favorite color is at index", colors.index(color), "in my list")
else:
    print("Sorry, I could not find your color")

#Ex6
range1 = range(0, 7)
range2 = range(1, 11, 3)
range3 = range(5, 0, -1)
range4 = range(6, -3, -2)

print(list(range1))
print(list(range2))
print(list(range3))
print(list(range4))

#EX7
def remove_dollar_sign(s):
    return s.replace("$", "")

#Ex8
def extract_even(l):
    return [x for x in l if x % 2 == 0]

print(extract_even([1, 4, 5, -1, 10]))

#Ex9
def factorial(n):
    result = 1

    for i in range(1, n + 1):
        result = result * i

    return result

print(factorial(5))

#Ex10
def get_divisors(n):
    divisors = []

    for i in range(1, n + 1):
        if n % i == 0:
            divisors.append(i)

    return divisors

print(get_divisors(12))

#Ex11
import math

def distance(x1, y1, x2, y2):
    return math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

print(distance(0, 0, 3, 4))

#Ex12
def print_pattern(m, n):
    for i in range(m):
        if i == 0 or i == m - 1:
            print("* " * n)
        else:
            print("* " + "  " * (n - 2) + "*")

print_pattern(4, 5)